// Supported hardware modules
enum SupportedModules {
  SONOFF_BASIC,
  SONOFF_RF,
  SONOFF_SV,
  SONOFF_TH,
  SONOFF_DUAL,
  SONOFF_POW,
  SONOFF_4CH,
  SONOFF_S2X,
  SLAMPHER,
  SONOFF_TOUCH,
  SONOFF_LED,
  CH1,
  CH4,
  MOTOR,
  ELECTRODRAGON,
  EXS_RELAY,
  WION,
  WEMOS,
  SONOFF_DEV,
  H801,
  SONOFF_SC,
  SONOFF_BN,
  SONOFF_4CHPRO,
  HUAFAN_SS,
  SONOFF_BRIDGE,
  SONOFF_B1,
  AILIGHT,
  SONOFF_T11,
  SONOFF_T12,
  SONOFF_T13,
  SUPLA1,
  WITTY,
  YUNSHAN,
  MAGICHOME,
  LUANIHVIO,
  KMC_70011,
  ARILUX_LC01,
  ARILUX_LC11,
  SONOFF_DUAL_R2,
  ARILUX_LC06,
  SONOFF_S31,
  ZENGGE_ZF_WF017,
  SONOFF_POW_R2,
  SONOFF_IFAN02,
  BLITZWOLF_BWSHP,
  SHELLY1,
  SHELLY2,
  PHILIPS,
  NEO_COOLCAM,
  ESP_SWITCH,
  OBI,
  TECKIN,
  APLIC_WDP303075,
  TUYA_DIMMER,
  GOSUND,
  ARMTRONIX_DIMMERS,
  SK03_TUYA,
  PS_16_DZ,
  TECKIN_US,
  MANZOKU_EU_4,
  OBI2,
  YTF_IR_BRIDGE,
  DIGOO,
  KA10,
  ZX2820,
  MI_DESK_LAMP,
  MAXMODULE };

  const uint8_t kModuleNiceList[MAXMODULE] PROGMEM = {
  SONOFF_BASIC,        // Sonoff Relay Devices
  SONOFF_RF,
  SONOFF_TH,
  SONOFF_DUAL,
  SONOFF_DUAL_R2,
  SONOFF_POW,
  SONOFF_POW_R2,
  SONOFF_4CH,
  SONOFF_4CHPRO,
  SONOFF_S31,          // Sonoff Socket Relay Devices with Energy Monitoring
  SONOFF_S2X,          // Sonoff Socket Relay Devices
  SONOFF_TOUCH,        // Sonoff Switch Devices
  SONOFF_T11,
  SONOFF_T12,
  SONOFF_T13,
  SONOFF_LED,          // Sonoff Light Devices
  SONOFF_BN,
  SONOFF_B1,           // Sonoff Light Bulbs
  SLAMPHER,
  SONOFF_SC,           // Sonoff Environmemtal Sensor
  SONOFF_IFAN02,       // Sonoff Fan
  SONOFF_BRIDGE,       // Sonoff Bridge
  SONOFF_SV,           // Sonoff Development Devices
  SONOFF_DEV,
  CH1,                 // Relay Devices
  CH4,
  MOTOR,
  ELECTRODRAGON,
  EXS_RELAY,
  SUPLA1,
  LUANIHVIO,
  YUNSHAN,
  WION,
  SHELLY1,
  SHELLY2,
  BLITZWOLF_BWSHP,     // Socket Relay Devices with Energy Monitoring
  TECKIN,
  TECKIN_US,
  APLIC_WDP303075,
  GOSUND,
  ZX2820,
  SK03_TUYA,
  DIGOO,
  KA10,
  NEO_COOLCAM,         // Socket Relay Devices
  OBI,
  OBI2,
  MANZOKU_EU_4,
  ESP_SWITCH,          // Switch Devices
  TUYA_DIMMER,         // Dimmer Devices
  ARMTRONIX_DIMMERS,
  PS_16_DZ,
  H801,                // Light Devices
  MAGICHOME,
  ARILUX_LC01,
  ARILUX_LC06,
  ARILUX_LC11,
  ZENGGE_ZF_WF017,
  HUAFAN_SS,
  MI_DESK_LAMP,
  KMC_70011,
  AILIGHT,             // Light Bulbs
  PHILIPS,
  YTF_IR_BRIDGE,
  WITTY,               // Development Devices
  WEMOS
};